RealPawParazzi/Backend

.github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md, build.gradle
- #3
Validation 라이브러리 추가
<br/>
- build.gradle에 spring-start-validation 추가
<br/>
어떤 변경 사항이 있나요?
=> [#3] Spring Validation 추가

src/main/java/paparazzi/back/Member.java, src/main/java/paparazzi/back/Pet.java, src/main/java/pawparazzi/back/BackApplication.java, src/main/java/pawparazzi/back/member/controller/MemberController.java, src/main/java/pawparazzi/back/member/dto/MemberLoginDto.java, src/main/java/pawparazzi/back/member/dto/MemberRegisterDto.java, src/main/java/pawparazzi/back/member/dto/MemberUpdateDto.java, src/main/java/pawparazzi/back/member/entity/Member.java, src/main/java/pawparazzi/back/member/exception/DuplicatedMemberException.java, src/main/java/pawparazzi/back/member/repository/MemberRepository.java, src/main/java/pawparazzi/back/member/service/MemberService.java
- #6
- 회원가입 및 로그인
- 패키지 이름 수정 (paparazzi -> pawparazzi)
- Main 클래스 추가
<br/>
- member 패키지 추가
<br/>
어떤 변경 사항이 있나요?
=> [FEAT] 회원 가입 및 로그인 기능

src/main/java/paparazzi/back/Member.java, src/main/java/paparazzi/back/Pet.java, src/main/java/pawparazzi/back/BackApplication.java, src/main/java/pawparazzi/back/member/controller/MemberController.java, src/main/java/pawparazzi/back/member/dto/MemberLoginDto.java, src/main/java/pawparazzi/back/member/dto/MemberRegisterDto.java, src/main/java/pawparazzi/back/member/dto/MemberUpdateDto.java, src/main/java/pawparazzi/back/member/entity/Member.java, src/main/java/pawparazzi/back/member/exception/DuplicatedMemberException.java, src/main/java/pawparazzi/back/member/repository/MemberRepository.java, src/main/java/pawparazzi/back/member/service/MemberService.java
- #6
- 회원가입 및 로그인
- 회원가입 오류 수정
<br/>
- 회원가입 오류 수정
<br/>
어떤 변경 사항이 있나요?
=> [FIX] 회원가입 및 로그인

src/main/java/pawparazzi/back/board/controller/BoardController.java, src/main/java/pawparazzi/back/board/dto/PostBoardRequestDto.java, src/main/java/pawparazzi/back/board/dto/PostBoardResponseDto.java, src/main/java/pawparazzi/back/board/dto/object/BoardListItem.java, src/main/java/pawparazzi/back/board/entity/Board.java, src/main/java/pawparazzi/back/board/entity/Image.java, src/main/java/pawparazzi/back/board/entity/Video.java, src/main/java/pawparazzi/back/board/repository/BoardRepository.java, src/main/java/pawparazzi/back/board/repository/ImageRepository.java, src/main/java/pawparazzi/back/board/repository/VideoRepository.java, src/main/java/pawparazzi/back/board/service/BoardService.java, src/main/java/pawparazzi/back/board/service/BoardServiceImplement.java, src/main/java/pawparazzi/back/comment/dto/object/CommentListItem.java, src/main/java/pawparazzi/back/comment/entity/Comment.java, src/main/java/pawparazzi/back/comment/repository/CommentRepository.java, src/main/java/pawparazzi/back/common/Dto/ResponseDto.java, src/main/java/pawparazzi/back/common/ResponseCode.java, src/main/java/pawparazzi/back/common/ResponseMessage.java, src/main/java/pawparazzi/back/favorite/dto/object/FavoriteListItem.java, src/main/java/pawparazzi/back/favorite/entity/Favorite.java, src/main/java/pawparazzi/back/favorite/entity/primaryKey/FavoritePk.java, src/main/java/pawparazzi/back/favorite/repository/FavoriteRepository.java, src/main/java/pawparazzi/back/member/entity/Member.java
- #2 
<br/>
- 게시물 작성 기능 및 게시물 작성을 위한 entity 생성, member entity userId -> id 로 변경
<br/>
어떤 변경 사항이 있나요?
- [] 빌드 부분 혹은 패키지 매니저 수정
=> [FEAT] 게시물 작성 기본 entity 및 게시물 작성 기능 추가

src/main/java/pawparazzi/back/member/controller/MemberController.java, src/main/java/pawparazzi/back/member/dto/MemberLoginDto.java, src/main/java/pawparazzi/back/member/entity/Member.java, src/main/java/pawparazzi/back/member/service/MemberService.java, src/main/java/pawparazzi/back/pet/controller/PetController.java, src/main/java/pawparazzi/back/pet/dto/PetRegisterRequestDto.java, src/main/java/pawparazzi/back/pet/dto/PetResponseDto.java, src/main/java/pawparazzi/back/pet/dto/PetUpdateDto.java, src/main/java/pawparazzi/back/pet/entity/Pet.java, src/main/java/pawparazzi/back/pet/exception/DuplicatedPetException.java, src/main/java/pawparazzi/back/pet/repository/PetRepository.java, src/main/java/pawparazzi/back/pet/service/PetService.java
- #9
회원별 펫 추가/조회/수정/삭제 기능 추가
<br/>
- pet 패키지 추가
- member 패키지 연관관계 매핑, 연관관계 메소드 추가, 일부 수정
<br/>
어떤 변경 사항이 있나요?
=> [FEAT] 펫 추가/조회/수정/삭제 기능 추가

src/main/java/pawparazzi/back/member/controller/MemberController.java, src/main/java/pawparazzi/back/member/dto/request/SignUpRequestDto.java, src/main/java/pawparazzi/back/member/entity/Member.java, src/main/java/pawparazzi/back/member/service/MemberService.java, src/main/java/pawparazzi/back/security/config/SecurityConfig.java, src/main/java/pawparazzi/back/security/filter/JwtAuthenticationFilter.java, src/main/java/pawparazzi/back/security/service/CustomUserDetailsService.java, src/main/java/pawparazzi/back/security/util/JwtUtil.java
- #16 
<br/>
- jwt 토큰 member Id 기반 토큰 생성 수정
- member 회원가입 시 name추가, 
- member 컨트롤러, 서비스 코드 수정
<br/>
어떤 변경 사항이 있나요?
=> [REFEAT] jwt member Id 기반 토큰 생성 수정

src/main/java/pawparazzi/back/board/controller/BoardController.java, src/main/java/pawparazzi/back/board/dto/BoardCreateRequestDto.java, src/main/java/pawparazzi/back/board/dto/BoardDetailDto.java, src/main/java/pawparazzi/back/board/dto/BoardListResponseDto.java, src/main/java/pawparazzi/back/board/entity/Board.java, src/main/java/pawparazzi/back/board/entity/BoardContent.java, src/main/java/pawparazzi/back/board/entity/BoardMedia.java, src/main/java/pawparazzi/back/board/entity/BoardOrder.java, src/main/java/pawparazzi/back/board/repository/BoardContentRepository.java, src/main/java/pawparazzi/back/board/repository/BoardMediaRepository.java, src/main/java/pawparazzi/back/board/repository/BoardOrderRepository.java, src/main/java/pawparazzi/back/board/repository/BoardRepository.java, src/main/java/pawparazzi/back/board/service/BoardService.java, src/main/java/pawparazzi/back/security/config/SecurityConfig.java, src/main/java/pawparazzi/back/security/user/CustomUserDetails.java
- #2 
<br/>
- board 패키지 추가
- 게시물 작성, 전체조회, 상세조회 기능 구현 
<br/>
어떤 변경 사항이 있나요?
- [] 빌드 부분 혹은 패키지 매니저 수정
=> [FEAT] 게시물 작성, 전체조회, 상세조회 기능

src/main/java/pawparazzi/back/exception/GlobalExceptionHandler.java, src/main/java/pawparazzi/back/member/controller/MemberController.java, src/main/java/pawparazzi/back/member/dto/request/UpdateMemberRequestDto.java, src/main/java/pawparazzi/back/member/dto/response/UpdateMemberResponseDto.java, src/main/java/pawparazzi/back/member/entity/Member.java, src/main/java/pawparazzi/back/member/service/MemberService.java, src/main/java/pawparazzi/back/security/config/SecurityConfig.java
[FEAT] 회원 정보 수정 , 탈퇴 기능 구현
- #25 
<br/>
- 회원 정보 수정, 탈퇴 기능 
- member 패키지 수정 
<br/>
어떤 변경 사항이 있나요?
- [] 빌드 부분 혹은 패키지 매니저 수정
=> [FEAT] 회원 정보 수정 , 탈퇴 기능 구현 

src/main/java/pawparazzi/back/board/controller/BoardController.java, src/main/java/pawparazzi/back/board/service/BoardService.java
[FEAT] 게시물 삭제, 특정 회원 게시물 조회 기능
- #28 
<br/>
- board 컨트롤러, 서비스 수정
- 특정회원 게시물 조회, 게시물 삭제 기능 구현
<br/>
어떤 변경 사항이 있나요?
- [] 빌드 부분 혹은 패키지 매니저 수정
=> [FEAT] 게시물 삭제, 특정 회원 게시물 조회 기능

src/main/java/pawparazzi/back/board/entity/Board.java, src/main/java/pawparazzi/back/likes/controller/LikeController.java, src/main/java/pawparazzi/back/likes/dto/LikeMemberDto.java, src/main/java/pawparazzi/back/likes/dto/LikeResponseDto.java, src/main/java/pawparazzi/back/likes/entity/Like.java, src/main/java/pawparazzi/back/likes/repository/LikeRepository.java, src/main/java/pawparazzi/back/likes/service/LikeService.java, src/main/java/pawparazzi/back/security/config/SecurityConfig.java
[FEAT] 좋아요 기능
- #34 
<br/>
- 좋아요 등록 / 취소 (토글) -  이미 좋아요를 누른 member가 다시 좋아요 버튼을 호출하면 좋아요가 취소됩니다
- 게시글 좋아요 누른 회원 목록 조회 - 좋아요를 누른 사용자의 닉네임과 프로필 이미지를 가져옵니다
<br/>
어떤 변경 사항이 있나요?
=> [FEAT] 좋아요 기능

src/main/java/pawparazzi/back/board/controller/BoardController.java, src/main/java/pawparazzi/back/board/service/BoardService.java
[Refactor] board패키지 jwt controller에서 관리하도록 변경
- #38 
<br/>
- board패키지 jwt 처리 방식 controlelr 에서 처리 후 service에 넘겨주도록 수정
<br/>
어떤 변경 사항이 있나요?
=> [Refactor] board패키지 코드 리펙터링

src/main/java/pawparazzi/back/comment/controller/CommentController.java, src/main/java/pawparazzi/back/comment/dto/CommentRequestDto.java, src/main/java/pawparazzi/back/comment/dto/CommentResponseDto.java, src/main/java/pawparazzi/back/comment/entity/Comment.java, src/main/java/pawparazzi/back/comment/repository/CommentRepository.java, src/main/java/pawparazzi/back/comment/service/CommentService.java, src/main/java/pawparazzi/back/exception/ApiErrorResponse.java, src/main/java/pawparazzi/back/exception/GlobalExceptionHandler.java, src/main/java/pawparazzi/back/security/config/SecurityConfig.java
[FEAT] 댓글 추가, 수정, 삭제, 조회 기능 추가
- #36
<br/>
- comment 패키지 추가
- 댓글 작성, 수정, 삭제, 조회 api 구현
- 댓글 삭제는 게시물을 작성한 사람, 댓글을 작상한 사람만 가능
- 댓글 조회시 댓글을 작성한 member의 닉네임과 프로필이미지 포함
<br/>
어떤 변경 사항이 있나요?
=> [FEAT] 댓글 추가, 수정, 삭제, 조회 기능 추가

src/main/java/pawparazzi/back/board/entity/Board.java, src/main/java/pawparazzi/back/comment/controller/CommentController.java, src/main/java/pawparazzi/back/comment/dto/CommentResponseWrapperDto.java, src/main/java/pawparazzi/back/comment/service/CommentService.java
[Refactor] 댓글 작성 시 게시물 commentCount 증가, 댓글 삭제 시 감소
- #41 
<br/>
-  댓글 작성 , 삭제 시 게시물 commentCount 값 증가 ,감소
<br/>
어떤 변경 사항이 있나요?
=> [Refactor] 댓글 작성 ,삭제 시 게시물 commentCount 증가 ,감소

src/main/java/pawparazzi/back/board/entity/Board.java, src/main/java/pawparazzi/back/board/service/BoardService.java, src/main/java/pawparazzi/back/comment/entity/Comment.java, src/main/java/pawparazzi/back/comment/repository/CommentLikeRepository.java, src/main/java/pawparazzi/back/comment/repository/CommentRepository.java, src/main/java/pawparazzi/back/likes/entity/Like.java, src/main/java/pawparazzi/back/likes/repository/LikeRepository.java
[Refactor] 게시물 삭제 시 맵핑 된 값 모두 삭제
- #44 
<br/>
- 게시물 삭제 시 맵핑 된 값 모두 삭제 ( 좋아요, 댓글, 댓글 좋아요)
<br/>
어떤 변경 사항이 있나요?
=> [Refactor] 게시물 삭제 시 맵핑 된 값 모두 삭제

src/main/java/pawparazzi/back/board/service/BoardService.java, src/main/java/pawparazzi/back/comment/controller/ReplyController.java, src/main/java/pawparazzi/back/comment/dto/request/ReplyRequestDto.java, src/main/java/pawparazzi/back/comment/dto/response/ReplyListResponseDto.java, src/main/java/pawparazzi/back/comment/dto/response/ReplyResponseDto.java, src/main/java/pawparazzi/back/comment/entity/Reply.java, src/main/java/pawparazzi/back/comment/repository/ReplyRepository.java, src/main/java/pawparazzi/back/comment/service/CommentService.java, src/main/java/pawparazzi/back/comment/service/ReplyService.java, src/main/java/pawparazzi/back/security/config/SecurityConfig.java
[FEAT] 대댓글 등록, 삭제, 수정, 특정 댓글의 대댓글 조회 기능
- #46 
<br/>
- 대댓글(reply) 등록, 수정, 삭제, 특정 댓글의 대댓글 조회 기능 추가
<br/>
어떤 변경 사항이 있나요?
=> [FEAT] 대댓글 등록, 삭제, 수정, 조회 기능

src/main/java/pawparazzi/back/board/entity/Board.java, src/main/java/pawparazzi/back/member/entity/Member.java
[Refactor] 게시물 코드 수정
- #51 
<br/>
- 게시물 무한 참조 코드 수정
<br/>
어떤 변경 사항이 있나요?
=> [Refactor] 게시물 코드 수정

src/main/java/pawparazzi/back/board/service/BoardService.java, src/main/java/pawparazzi/back/comment/controller/ReplyController.java, src/main/java/pawparazzi/back/comment/dto/response/ReplyLikeResponseDto.java, src/main/java/pawparazzi/back/comment/dto/response/ReplyLikesResponseDto.java, src/main/java/pawparazzi/back/comment/entity/Comment.java, src/main/java/pawparazzi/back/comment/entity/Reply.java, src/main/java/pawparazzi/back/comment/entity/ReplyLike.java, src/main/java/pawparazzi/back/comment/repository/ReplyLikeRepository.java, src/main/java/pawparazzi/back/comment/repository/ReplyRepository.java, src/main/java/pawparazzi/back/comment/service/ReplyLikeService.java, src/main/java/pawparazzi/back/comment/service/ReplyService.java
[FEAT] 대댓글 좋아요 등록 / 취소, 누른 회원 조회 기능
- #50 
<br/>
- 대댓글 좋아요 / 취소 (토글)
- 대댓글 좋아요 누른 회원 상세 정보 GET
<br/>
어떤 변경 사항이 있나요?
=> [FEAT] 대댓글 좋아요 기능

build.gradle, src/main/java/pawparazzi/back/BackApplication.java, src/main/resources/application.yml
[FEAT] 카카오 로그인 기본 틀 구성
- #54 
<br/>
- 기초 설치파일 , env등 구성
<br/>
어떤 변경 사항이 있나요?
=> [FEAT] 카카오 로그인 기본 틀 구성

src/main/java/pawparazzi/back/pet/entity/Type.java
- #9
<br/>
- 반려동물 Type enum 값을 강아지, 고양이에서 DOG, CAT 으로 변경
<br/>
어떤 변경 사항이 있나요?
=> fix: 반려동물 타입 수정

src/main/java/pawparazzi/back/likes/controller/LikeController.java, src/main/java/pawparazzi/back/security/config/SecurityConfig.java
[Refactor] 게시물 엔드포인트 수정
- #57 
<br/>
- 게시물 좋아요 엔드포인트 , 댓글 대댓글 과 동일한 형태로 수정
<br/>
어떤 변경 사항이 있나요?
=> [Refactor] 게시물 좋아요 엔드포인트 수정

src/main/java/pawparazzi/back/board/dto/BoardListResponseDto.java, src/main/java/pawparazzi/back/board/entity/Board.java, src/main/java/pawparazzi/back/board/repository/BoardMongoRepository.java, src/main/java/pawparazzi/back/board/repository/BoardRepository.java, src/main/java/pawparazzi/back/board/service/BoardService.java, src/main/java/pawparazzi/back/comment/entity/Comment.java, src/main/java/pawparazzi/back/comment/entity/Reply.java, src/main/java/pawparazzi/back/comment/repository/ReplyRepository.java, src/main/java/pawparazzi/back/comment/service/CommentService.java, src/main/java/pawparazzi/back/member/entity/Member.java, src/main/java/pawparazzi/back/member/service/MemberService.java
[FIX] 양방향 참조 문제 해결
- #62
<br/>
- 게시물, 맴버, 좋아요, 댓글, 대댓글 등 양방향 참조 문제 해결
<br/>
어떤 변경 사항이 있나요?
=> [FIX] 양방향 참조 문제 해결

src/main/java/pawparazzi/back/comment/dto/response/CommentLikeResponseDto.java, src/main/java/pawparazzi/back/comment/dto/response/ReplyLikeResponseDto.java, src/main/java/pawparazzi/back/comment/service/CommentLikeService.java, src/main/java/pawparazzi/back/comment/service/ReplyLikeService.java, src/main/java/pawparazzi/back/likes/controller/LikeController.java, src/main/java/pawparazzi/back/likes/dto/LikeToggleResponseDto.java, src/main/java/pawparazzi/back/likes/service/LikeService.java
[Refactor] 모든 좋아요 response Body 값 수정
- #64 
<br/>
- 모든 좋아요 response Body 값 수정
<br/>
어떤 변경 사항이 있나요?
=> [Refactor] 모든 좋아요 response Body 값 수정

src/main/java/pawparazzi/back/board/entity/Board.java, src/main/java/pawparazzi/back/board/service/BoardService.java
[FEAT] 게시물 조회수 증가 기능 추가
- #68 
<br/>
- board service,entity 기능 추가
<br/>
어떤 변경 사항이 있나요?
=> [FEAT] 게시물 조회수 증가 기능

src/main/java/pawparazzi/back/follow/controller/FollowController.java, src/main/java/pawparazzi/back/follow/service/FollowService.java
- #14
<br/>
- 팔로우 기능 동작 시 사용자의 아이디로 구분
<br/>
어떤 변경 사항이 있나요?
=> [Refactor] 팔로우 기능 사용자 아이디로 변경

src/main/java/pawparazzi/back/security/config/SecurityConfig.java
- #14
<br/>
- /api/follow/** 추가
<br/>
어떤 변경 사항이 있나요?
=> [REFACTOR]: SecurityConfig에 requestMatchers 추가

src/main/java/pawparazzi/back/follow/dto/FollowerResponseDto.java, src/main/java/pawparazzi/back/follow/dto/FollowingResponseDto.java, src/main/java/pawparazzi/back/follow/service/FollowService.java
- #14
<br/>
- 팔로워 및 팔로잉 목록 조회 시 해당 사용자의 아이디 조회할 수 있도록 추가
<br/>
어떤 변경 사항이 있나요?
=> [REFACTOR] 팔로워 및 팔로잉 목록 조회 시 해당 사용자의 아이디 조회할 수 있도록 추가

build.gradle, src/main/java/pawparazzi/back/config/JacksonConfig.java
[FIX] 에러 수정
- #82 
<br/>
- 실행오류 수정
<br/>
어떤 변경 사항이 있나요?
=> [FIX] 에러 수정

src/main/java/pawparazzi/back/walk/controller/WalkController.java, src/main/java/pawparazzi/back/walk/dto/LocationPointDto.java, src/main/java/pawparazzi/back/walk/dto/WalkRequestDto.java, src/main/java/pawparazzi/back/walk/dto/WalkResponseDto.java, src/main/java/pawparazzi/back/walk/entity/LocationPoint.java, src/main/java/pawparazzi/back/walk/entity/Walk.java, src/main/java/pawparazzi/back/walk/entity/WalkMapper.java, src/main/java/pawparazzi/back/walk/repository/WalkRepository.java, src/main/java/pawparazzi/back/walk/service/WalkService.java
- #73
<br/>
- walk 패키지 추가
- 산책 기록 저장/조회(날짜/펫/날짜&펫)/삭제 기능 추가
<br/>
어떤 변경 사항이 있나요?
=> [FEAT] 산책 기록 기능

src/main/java/pawparazzi/back/member/controller/AuthController.java
[FIX] kakao 오류 수정
- #88 
<br/>
- 카카오 로그인 controller return 값 수정 
<br/>
어떤 변경 사항이 있나요?
=> [FIX] kakao 오류 수정

src/main/java/pawparazzi/back/member/controller/AuthController.java, src/main/java/pawparazzi/back/walk/controller/WalkController.java, src/main/java/pawparazzi/back/walk/dto/LocationPointDto.java, src/main/java/pawparazzi/back/walk/dto/WalkRequestDto.java, src/main/java/pawparazzi/back/walk/dto/WalkResponseDto.java, src/main/java/pawparazzi/back/walk/entity/LocationPoint.java, src/main/java/pawparazzi/back/walk/entity/Walk.java, src/main/java/pawparazzi/back/walk/repository/WalkRepository.java, src/main/java/pawparazzi/back/walk/service/WalkService.java
- #73
<br/>
- ZonedDateTime에서 LocalDateTime으로 변경
<br/>
어떤 변경 사항이 있나요?
=> [REFACTOR] 산책 기록 LocalDateTime으로 변경

src/main/java/pawparazzi/back/S3/S3UploadUtil.java, src/main/java/pawparazzi/back/S3/service/S3AsyncService.java, src/main/java/pawparazzi/back/board/controller/BoardController.java, src/main/java/pawparazzi/back/board/dto/BoardCreateRequestDto.java, src/main/java/pawparazzi/back/board/dto/BoardUpdateRequestDto.java, src/main/java/pawparazzi/back/board/service/BoardService.java, src/main/java/pawparazzi/back/pet/controller/PetController.java, src/main/java/pawparazzi/back/pet/service/PetService.java
[FEAT] 게시물 S3 기능 연동
- #90 
<br/>
- 게시물 작성, 수정 ,삭제 로직 S3연동 후 시각화 
- 게시물 작성, 수정 = json방식에서 form-data형식으로 변경
<br/>
어떤 변경 사항이 있나요?
=> [FEAT] 게시물 S3 기능 연동

.github/workflows/deploy.yml
- #95
<br/>
- deploy.sh 실행 권한 추가
<br/>
어떤 변경 사항이 있나요?
=> fix: deploy.yml에 실행 권한 스크립트 추가

src/main/java/pawparazzi/back/board/controller/BoardController.java
[Refactor] borad 불필요한 생성자 제거
- #97 
<br/>
-  private final ObjectMapper objectMapper; 를 추가하여 코드 내 불필요한 생성자 제거
<br/>
어떤 변경 사항이 있나요?
=> [Refactor] borad 불필요한 생성자 제거

.github/workflows/deploy.yml
- #95
<br/>
- 배포 파이프라인 트리거
<br/>
어떤 변경 사항이 있나요?
=> [FEAT]: 배포 파이프라인 트리거

.github/workflows/deploy.yml
- #95
<br/>
- 배포 파이프라인 트리거2
<br/>
어떤 변경 사항이 있나요?
=> [CHORE]: 배포 파이프라인 트리거2

src/main/java/pawparazzi/back/member/controller/MemberController.java, src/main/java/pawparazzi/back/member/entity/RefreshToken.java, src/main/java/pawparazzi/back/member/repository/RefreshTokenRepository.java, src/main/java/pawparazzi/back/member/service/MemberService.java, src/main/java/pawparazzi/back/security/filter/JwtAuthenticationFilter.java, src/main/java/pawparazzi/back/security/util/JwtUtil.java
[FIX] refreshToken 발급 방식으로 변경
- #103 
<br/>
- 로그인 시  access Token , refresh Token 발급 
- access Token 만료 시 refresh Token를 통해 access Token 다시 발급
<br/>
어떤 변경 사항이 있나요?
=> [FIX] refreshToken 발급 방식으로 변경

src/main/java/pawparazzi/back/member/service/MemberService.java
[FIX] 회원 정보 수정 오류 수정
- #105 
<br/>
- 프로필 이미지를 수정하지 않더라도 기본이미지로 프로필이 바뀌지 않게 수정
<br/>
어떤 변경 사항이 있나요?
=> [FIX] 회원 정보 수정 오류 수정

src/main/java/pawparazzi/back/board/controller/BoardController.java, src/main/java/pawparazzi/back/comment/controller/CommentController.java, src/main/java/pawparazzi/back/follow/controller/FollowController.java, src/main/java/pawparazzi/back/likes/controller/LikeController.java, src/main/java/pawparazzi/back/member/controller/MemberController.java, src/main/java/pawparazzi/back/member/service/MemberService.java, src/main/java/pawparazzi/back/security/config/SecurityConfig.java, src/main/java/pawparazzi/back/security/filter/JwtAuthenticationFilter.java, src/main/java/pawparazzi/back/security/util/JwtUtil.java, src/main/java/pawparazzi/back/walk/controller/WalkController.java
[FIX] 401 오류로 변경
- #107 
<br/>
-  만료된 토큰 사용시 401 UNAUTHORIZED 발생
<br/>
어떤 변경 사항이 있나요?
=> [FIX] 만료된 토큰 사용시 401 UNAUTHORIZED 발생

src/main/java/pawparazzi/back/member/controller/AuthController.java, src/main/java/pawparazzi/back/member/controller/MemberController.java, src/main/java/pawparazzi/back/member/service/MemberService.java
[FIX] kakao 로그인 refresh토큰 발급
- #109 
<br/>
- member 패키지 kakao 로그인 cotroller, service 로직 수정 -> refresh 토큰 발급 
<br/>
어떤 변경 사항이 있나요?
=> [FIX] kakao 로그인 refresh토큰 발급

src/main/java/pawparazzi/back/board/controller/BoardController.java, src/main/java/pawparazzi/back/board/service/BoardService.java, src/main/java/pawparazzi/back/likes/controller/LikeController.java, src/main/java/pawparazzi/back/member/controller/MemberController.java, src/main/java/pawparazzi/back/member/service/MemberService.java, src/main/java/pawparazzi/back/security/config/SecurityConfig.java, src/main/java/pawparazzi/back/security/user/CustomUserDetails.java
[Refactor] 멤버, 게시물, 좋아요 controller, service 분리
- #111 
<br/>
- controller에서 직접 토큰 처리 x 
- controller에서 직접 에러 처리 x 
<br/>
어떤 변경 사항이 있나요?
=> [Refactor] 멤버, 게시물, 좋아요 controller, service 분리

src/main/java/pawparazzi/back/member/entity/Member.java, src/main/java/pawparazzi/back/place/controller/PlaceController.java, src/main/java/pawparazzi/back/place/dto/PlaceRequestDto.java, src/main/java/pawparazzi/back/place/dto/PlaceResponseDto.java, src/main/java/pawparazzi/back/place/entity/Place.java, src/main/java/pawparazzi/back/place/repository/PlaceRepository.java, src/main/java/pawparazzi/back/place/service/PlaceService.java
- #48
<br/>
-  즐겨찾는 장소 저장/조회/수정/삭제 기능 추가
<br/>
어떤 변경 사항이 있나요?
=> [FEAT]: 즐겨찾는 장소 저장/조회/수정/삭제 기능 추가
